openapi: 3.0.0
info:
  title: ResumeAPI
  description: >-
    An API standard for retrieving resumes in JSON format, conformant with the JSON resume standard:
    https://jsonresume.org/
  version: 1.3.0
  contact:
    url: https://support.thorpincorp.com

# tags:
#   - name: Resume
#     description: A full json-resume compliant resume for a specific user
#   - name: Resource
#     description: >-
#       An individual resource item associated with a users resume. For example, work history

servers:
  - url: https://resume.thorpincorp.com
    description: Production resume API server
  - url: https://localhost:3000
    description: Local development server

security:
  - ResumapiSecurityScheme:
      - resume:read
      - resume:write
      - resource:read
      - resource:write

paths:
  /resume:
    get:
      operationId: GetResume
      description: Get full resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:read
    post:
      operationId: CreateResume
      description: Create new resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
    put:
      operationId: UpdateResume
      description: Update resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
    delete:
      operationId: DeleteResume
      description: Delete resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
  /basics:
    get:
      operationId: GetBasics
      description: Get resume summary
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateBasics
      description: Update resume summary
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /work:
    get:
      operationId: GetWorkEntries
      description: Get all resume work history entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateWorkEntry
      description: Create resume work history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /work/{id}:
    get:
      operationId: GetWorkEntry
      description: Get specific resume work history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateWorkEntry
      description: Update specific resume work history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteWorkEntry
      description: Delete specific resume work history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /volunteer:
    get:
      operationId: GetVolunteerEntries
      description: Get all resume volunteering history entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateVolunteerEntry
      description: Get specific resume volunteering history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /volunteer/{id}:
    get:
      operationId: GetVolunteerEntry
      description: Get specific resume volunteering history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateVolunteerEntry
      description: Update specific resume volunteering history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteVolunteerEntry
      description: Delete specific resume volunteering history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /education:
    get:
      operationId: GetEducationEntries
      description: Get all resume education history entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateEducationEntry
      description: Create specific resume education history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /education/{id}:
    get:
      operationId: GetEducationEntry
      description: Get specific resume education history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateEducationEntry
      description: Update specific resume education history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteEducationEntry
      description: Delete specific resume education history entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /awards:
    get:
      operationId: GetAwards
      description: Get all resume award entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateAwards
      description: Create a resume award entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /awards/{id}:
    get:
      operationId: GetAward
      description: Get a specific resume award entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateAward
      description: Update a specific resume award entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteAward
      description: Delete a specific resume award entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /certificates:
    get:
      operationId: GetCertificates
      description: Get all resume certificate entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateCertificate
      description: Create a resume certificate entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /certificates/{id}:
    get:
      operationId: GetCertificate
      description: Get a specific resume certificate entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateCertificate
      description: Update a specific resume certificate entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteCertificate
      description: Delete a specific resume certificate entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /publications:
    get:
      operationId: GetPublications
      description: Get all resume publication entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreatePublication
      description: Create a resume publication entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /publications/{id}:
    get:
      operationId: GetPublication
      description: Get a specific resume publication entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdatePublication
      description: Update a specific resume publication entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeletePublication
      description: Delete a specific resume publication entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /skills:
    get:
      operationId: GetSkills
      description: Get all resume skill entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateSkill
      description: Create a resume skill entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /skills/{id}:
    get:
      operationId: GetSkill
      description: Get a specific resume skill entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateSkill
      description: Update a specific resume skill entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteSkill
      description: Delete a specific resume skill entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /languages:
    get:
      operationId: GetLanguages
      description: Get all resume language entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateLanguage
      description: Create a resume language entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /languages/{id}:
    get:
      operationId: GetLanguage
      description: Get a specific resume language entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateLanguage
      description: Update a specific resume language entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteLanguage
      description: Delete a specific resume language entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /interests:
    get:
      operationId: GetInterests
      description: Get all resume interest entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateInterest
      description: Create a resume interest entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /interests/{id}:
    get:
      operationId: GetInterest
      description: Get a specific resume interest entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateInterest
      description: Update a specific resume interest entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteInterest
      description: Delete a specific resume interest entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /references:
    get:
      operationId: GetReferences
      description: Get all resume reference entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateReference
      description: Create a resume reference entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /references/{id}:
    get:
      operationId: GetReference
      description: Get a specific resume reference entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateReference
      description: Update a specific resume reference entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteReference
      description: Delete a specific resume reference entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /projects:
    get:
      operationId: GetProjects
      description: Get all resume project entries
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      operationId: CreateProject
      description: Create a resume project entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /projects/{id}:
    get:
      operationId: GetProject
      description: Get a specific resume project entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      operationId: UpdateProject
      description: Update a specific resume project entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      operationId: DeleteProject
      description: Delete a specific resume project entry
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
components:
  securitySchemes:
    ResumapiSecurityScheme:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth2/token
          scopes:
            resume:read: Read resume
            resume:write: Modify or delete resume
            resource:read: Read resume data
            resource:write: Create or update resume data
