openapi: 3.0.0
info:
  title: ResumeAPI
  description: >-
    An API standard for retrieving resumes in JSON format, predominantly aligned with the JSON resume standard:
    https://jsonresume.org/
  version: 1.1.0

tags:
  - name: Resume
    description: A full json-resume compliant resume for a specific user
  - name: Resource
    description: >-
      An individual resource item associated with a users resume. For example, work history

servers:
  - url: https://resume.thorpincorp.com/
    description: Production resume API server
  - url: https://localhost:3000/
    description: Local development server

security:
  - ResumapiSecurityScheme:
      - resume:read
      - resume:write
      - resource:read
      - resource:write

paths:
  /resume:
    get:
      summary: Get Resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:read
    post:
      summary: Create Resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
    put:
      summary: Update Resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
    delete:
      summary: Delete Resume
      tags:
        - Resume
      security:
        - ResumapiSecurityScheme:
            - resume:write
  /basics:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /work:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /work/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /volunteer:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /volunteer/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /education:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /education/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /awards:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /awards/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /certificates:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /certificates/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /publications:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /publications/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /skills:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /skills/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /languages:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /languages/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /interests:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /interests/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /references:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /references/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /projects:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    post:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
  /projects/{id}:
    get:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:read
    put:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
    delete:
      tags:
        - Resource
      security:
        - ResumapiSecurityScheme:
            - resource:write
components:
  securitySchemes:
    ResumapiSecurityScheme:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth2/token
          scopes:
            resume:read: Read resume
            resume:write: Modify or delete resume
            resource:read: Read resume data
            resource:write: Create or update resume data
