name: Run Spectral OpenAPI Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Spectral Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run Spectral Linter
        run: yarn lint
        
      - name: Update status badge
        if: ${{ success() }}
        run: |
          echo "[![Lint](https://github.com/slatei/ResumAPI/actions/workflows/lint.yml/badge.svg)](https://github.com/slatei/ResumAPI/actions/workflows/lint.yml)" > badge.md
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add badge.md
          git commit -m "Update status badge"
          git push
